CREATE TABLE usuarios(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(200) NOT NULL UNIQUE,
    senha VARCHAR(300) NOT NULL,
    nome VARCHAR(200) NOT NULL,
    idade VARCHAR(3)NOT NULL

);

